#!/bin/bash


#$ -m a
#$ -V
#$ -l h_vmem=16G
#$ -M gordonam@stanford.edu

module load MATLAB-R2012b
cd /home/gordonam/ef
#rm "/home/gordonam/pm/stout$sVar"
#rm "/home/gordonam/pm/sterr$sVar"

matlab -nodesktop -r "exMat('$sVar')"

